# version: '3.8'

# services:
#   backend:
#     build: .
#     depends_on:
#       - mysql
#     environment:
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_PASSWORD: strong10
#       MYSQL_DATABASE: hrmonitor
#     ports:
#       - "8080:8080"

#   mysql:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: strong10
#       MYSQL_DATABASE: hrmonitor
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data: